name: Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - run: git pull origin main 
        with:
          fetch-depth: 0

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: cat -v packages/components/src/button/index.tsx && cat -v packages/components/src/button/index.stories.tsx  

      - name: Lint
        run: npm run lint:ci


