# TODO - remove this and associated publish scripts in the repo

# name: Publish New NPM packages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   publish:
#     name: Publish
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#       - run: npm ci

#       - name: Build scripts
#         run: npm run build -w packages/scripts
      
#       - name: Ensure scripts are avail in monorepo
#         run: npm ci

#       - name: Publish new versions to npm
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#         run: npm run publish:npm